### ISSUE TITLE
Question:  upgrade to Godot4?

### ISSUE THREAD

**Issue by jasonswearingen** [Fractural/GodotFixedVolatilePhysics#3]
Any plans to update to Godot 4?  or waiting for 4.1?  (Mobile support)

**Comment by Atlinx** [comment]
So far, I'm keeping this in Godot 3.x. With 4.x's release, I believe Snopek Game's is planning on releasing a GDExtension version of his fixed point physics plugin. Once that's released I can release a C# wrapper library for it.

**Comment by robochase6000** [comment]
hey sorry to dig this up again, but I'm curious about this as well. I was looking at snopek's SG Physics 2D GDExtension, but I was having trouble getting c# to use the library - did you end up making a wrapper for it @Atlinx ?

this repo seems promising too, but it seems to have a lot of issues in godot 4.

**Comment by Atlinx** [comment]
Unfortunately, I have not made a C# wrapper for Snopek Games' GDExtension yet since I've been busy with other work. In the meantime, you can probably interact with the GDExtension classes using the `call` and `get` methods that Godot Objects have. [See here ](https://www.reddit.com/r/godot/comments/zlglpk/is_it_possible_to_call_gdextension_code_from_c/) for someone who was also trying to use GDExtensions in C#.

**Comment by robochase6000** [comment]
thanks for the reply.  if I'm understanding that link correctly, I should follow these steps to build my own c# wrapper? https://github.com/DmitriySalnikov/godot_debug_draw_3d/issues/2#issuecomment-1406989099

a little complicated sounding, but I can give it a shot 😅
